do_mlm: true
num_bins: 51
sampling: true
pad_value: -2
data_style: both
do_binning: true
do_padding: true
mask_value: -1
max_length: 1024
right_binning: false
mlm_probability: 0.5
use_junk_tokens: false
use_pert_token: true
pert_to_id_path:
  remote: "s3://fleetwood/orion/pert_to_id.json"
  local: "pert_to_id.json"
keep_first_n_tokens: 2
pad_token_id: 0
